# Generated by Django 5.2.2 on 2025-06-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0004_userprofile_address_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
