# Generated by Django 5.2.2 on 2025-06-16 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0006_alter_userprofile_phone_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 6, 16)),
            preserve_default=False,
        ),
    ]
