# Generated by Django 5.2.2 on 2025-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0008_promocode_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='available_dates',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateField(),
        ),
    ]
