# Generated by Django 5.2.2 on 2025-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0010_remove_package_image_packageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
