# Generated by Django 5.2.2 on 2025-06-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0012_remove_package_image_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
