# Generated by Django 5.2.2 on 2025-06-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0014_remove_package_image_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
