# Generated by Django 5.2.2 on 2025-06-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0015_package_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='brochure',
        ),
    ]
