# Generated by Django 5.2.2 on 2025-06-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0019_booking_discount_booking_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='platform_charge',
            field=models.DecimalField(decimal_places=2, default=154.0, max_digits=10),
        ),
    ]
