# Generated by Django 5.2.2 on 2025-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigo', '0020_alter_booking_platform_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='platform_charge',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=10),
        ),
    ]
